### ISSUE TITLE
ERRO no micro-videos-db 

### ISSUE THREAD

**Issue by felipefariasdasilva** [codeedu/laravel-microservice-quickstart#17]
Estou tendo o seguinte erro:

`micro-videos-db | 2021-03-19 17:32:31+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.33-1debian10 started.
micro-videos-db | 2021-03-19 17:32:32+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
micro-videos-db | 2021-03-19 17:32:32+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.33-1debian10 started.
micro-videos-db | 2021-03-19 17:32:32+00:00 [ERROR] [Entrypoint]: MYSQL_USER="root", MYSQL_PASSWORD cannot be used for the root
user
micro-videos-db |     Use one of the following to control the root user password:
micro-videos-db |     - MYSQL_ROOT_PASSWORD
micro-videos-db |     - MYSQL_ALLOW_EMPTY_PASSWORD
micro-videos-db |     - MYSQL_RANDOM_ROOT_PASSWORD`

poderia me ajudar?

**Comment by jonatasrafael** [comment]
Bom dia Felipe, tive o mesmo erro, só retirar a linha 48 do docker.compose.yaml
`- MYSQL_USER=root`
O erro é por causa dela.

**Comment by felipefariasdasilva** [comment]
> Bom dia Felipe, tive o mesmo erro, só retirar a linha 48 do docker.compose.yaml
> 
> `- MYSQL_USER=root`
> 
> O erro é por causa dela.

Obrigado @jonatasrafael, deu certo aqui!!
