### ISSUE TITLE
[Dúvida] Git - Modo Interativo

### ISSUE THREAD

**Issue by renatocinttra** [codeedu/laravel-microservice-quickstart#28]
Olá Luiz,

Eu inicie o primeiro módulo de micro serviço. Estou me aproximando das tecnologias (Laravel, Docker, WSL, entre outros) abordadas nesse módulo. Consegui realizar a configuração do meu ambiente de desenvolvimento e avancei até a aula que trata da criação do Model Category. Alguns ajustes na syntax do código mas consegui concluí essa aula.

No entanto, você comenta da possibilidade de realizer o Pull/Request de dentro do Container direto para a conta do Github, por esse motivo foi adicionado o recurso do Git no arquivo do Dockerfile.

Porém, o comando git add -i que é o modo interativo do git não funcionou. Observei que a versão do git adicionado na imagem não é a versão mais recente. Então tentei rodar o seguinte comando no Dockerfile:

RUN apk update git 

E também o comando  

RUN apk update && upgrade  git

Sem sucesso. É possível atualizar a versão git de modo a funcionar o comando git add -i ?

Desde já agradeço.

**Comment by argentinaluiz** [comment]
Olá Renato (@renatocinttra ), tudo bem?

Usando a imagem PHP deste repositório, a versão do Git instalada será a 2.26.
Cada versão do Alpine já terá, por padrão sua compatibilidade com os pacotes a serem instalados.
É possível fazer update dos pacotes adicionando algum repositório que aponte a nova versão ou instalando diretamente no terminal sem o `apk add`.

Neste caso, recomendo fazer algum mais simples, use uma imagem mais recente do PHP 7.3 que contenha uma versão do Alpine mais recente, como o Alpine 3.12, o FROM da imagem ficará assim:

```
FROM php:7.3.19-alpine3.12
```

Faça o build novamente e me fale se conseguiu evoluir com isto, ok?

Qualquer dúvida, estamos à disposição.

;)
